Models/ErrorViewModel.cs
namespace AjaxApi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CrudController.cs
using Microsoft.AspNetCore.Mvc;

namespace AjaxApi.Controllers
{
    public class CrudController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail() {
            return View();
        }
    }
}

Controllers/HomeController.cs
using AjaxApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AjaxApi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Crud/Detail.cshtml
<script src="~/js/crudoperation/detail.js"></script>

<h5>Add New Record - </h5>
<hr />

<div class="col-6">
    <div class="form-group">
        <input type="hidden" id="hdnCrudId" value="0" />
        <label class="col-md-3 col-xs-3 control-label" for="txtUserName">UserName</label>
        <div class="col-md-7 col-xs-7">
            <input type="text" class="form-control" id="txtUserName" />
        </div>
    </div>
    <br />
    <div class="form-group">
        <label class="col-md-3 col-xs-3 control-label" for="txtAge">Age</label>
        <div class="col-md-7 col-xs-7">
            <input type="text" class="form-control" id="txtAge" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="spacer5">
            <div class="col-md-12 col-xs-12">
                <ul class="list-group">
                    <li class="list-group-item centerAlign">
                        <button id="btnSave" class="btn btn-success" type="button">Save</button>
                        <button id="btnClose" class="btn btn-danger" type="button">Close</button>
                        <button id="btnClear" class="btn btn-primary" type="button">Clear</button>
                        <button id="btnDelete" class="btn btn-danger" type="button">Delete</button>
                    </li>
                </ul>

            </div>

        </div>
    </div>


</div>

Views/Crud/Index.cshtml
<script src="~/js/crudoperation/crudoperation.js"></script>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* <h1>Index</h1> *@



<div id="divDetail" style="display:none">
    @Html.Partial("Detail")
</div>

<div id="divSummary">
    @Html.Partial("Summary")
</div> 

Views/Crud/Summary.cshtml
<script src="~/js/crudoperation/summary.js"></script>

<div class="row">
    <div class="col-12">
        All Records - 
    </div>
    <hr />
    <br />
    <div class="col-md-12">
        <button class="btn btn-success" id="btnAdd">Add Record</button>
        <br />
        <table class="table table-stripped" id="Table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>UserName</th>
                    <th>Age</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-4">Welcome</h3>
    <p>ASP.NET Web API CRUD using jQuery Ajax and Views</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjaxApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AjaxApi.styles.css" asp-append-version="true" />
    <a href="~/lib/jquery/dist/jquery.min.map"></a>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/common.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AjaxApi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Crud" asp-action="Index">Crud</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AjaxApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>